name: Build

on: ["workflow_dispatch"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install clang llvm-dev uuid-dev
    - name: configure
      run: CC="clang -arch arm64" CXX="clang++ -arch -arm64" ./cctools/configure --prefix=/home/runner/prebuild
    - name: make
      run: CC="clang -arch arm64" CXX="clang++ -arch -arm64" make -j$(nproc)
    - name: install
      run: make install
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
         # Artifact name
          name: Prebuild
          path: /home/runner/prebuild
