name: Build

on: ["workflow_dispatch"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install clang llvm-dev uuid-dev
    - name: configure
      run: CC="clang --target=aarch64-unknown-linux-gnu" CXX="clang++ --target=aarch64-unknown-linux-gnu" ./cctools/configure --prefix=/home/runner/prebuild
    - name: make
      run: CC="clang --target=aarch64-unknown-linux-gnu" CXX="clang++ --target=aarch64-unknown-linux-gnu" make -j$(nproc)
    - name: install
      run: make install
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
         # Artifact name
          name: Prebuild
          path: /home/runner/prebuild
